from turtle import *
from functions import *
from datetime import datetime
from time import *
speed(1000)
hideturtle()
def cadre():
    penup()
    goto(0,-60)
    pendown()
    circle(100)
    penup()
    goto(0,28)
    fillcolor('black')
    pendown()
    begin_fill()
    circle(4)
    end_fill()
while True:
    clear()
    color('black')
    cadre()
    temps_actuel = datetime.now().strftime("%H:%M:%S")
    temps_liste=temps_actuel.split(':')
    temps_liste=[int(temps_liste[i]) for i in range(3)]
    print(temps_liste)
    color('black')
    left(90)
    right(360/12*temps_liste[0])
    forward(50)
    left(360/12*temps_liste[0])
    goto(0,28)
    #left(90)
    right(360/60*temps_liste[1])
    color('blue')
    forward(40)
    left(360/60*temps_liste[1])
    #left(90)
    right(360/60*temps_liste[2])
    goto(0,28)
    color('red')
    forward(30)
    left(360/60*temps_liste[2])
    right(90)
    sleep(1)
mainloop()